### ISSUE TITLE
DetailedResponse's _to_dict function does not properly handle JSON arrays

### ISSUE THREAD

**Issue by emlaver** [IBM/python-sdk-core#13]
If the JSON response is an array, the `_to_dict` will return `HTTP Response`:

Code snippet from `DetailedResponse`:
```
    def _to_dict(self):
        _dict = {}
        if hasattr(self, 'result') and self.result is not None:
            _dict['result'] = self.result if isinstance(self.result, dict) else 'HTTP response'
        ...
``` 
What I'd expect:
The response object returns an array of items

A quick fix would be to check if the `result` is an instance of a `list`:
```
        if hasattr(self, 'result') and self.result is not None:
            _dict['result'] = self.result if isinstance(self.result, dict) or isinstance(self.result, list)  else 'HTTP response'
```

**Comment by germanattanasio** [comment]
Thanks a lot for filing this issue! Would you like to write a PR for this? I'd be more than happy to walk you through the steps involved
