### ISSUE TITLE
vault-token vs. sa-token

### ISSUE THREAD

**Issue by data-henrik** [IBM/python-sdk-core#164]
For Compute Resource authentication through Kubernetes (Container Authentication), the IKS docs use `sa-token` in their examples: https://cloud.ibm.com/docs/containers?topic=containers-pod-iam-identity&interface=ui

Why is this core SDK using `vault-token` as default? Some sync required to improve user experience. Initially, I ran into an error assuming that the default value in the SDK would match the default...

**Comment by padamstx** [comment]
PRs:
- https://github.com/IBM/go-sdk-core/pull/183
- https://github.com/IBM/java-sdk-core/pull/202

**Comment by padamstx** [comment]
I noticed that this issue is still open.  I checked on the various core libraries (Go, Java, Node.js and Python) and this request has been implemented in each one.
Closing the issue...
