### ISSUE TITLE
Support for urllib3 2.x.x

### ISSUE THREAD

**Issue by bradhvr** [IBM/python-sdk-core#178]
Hello, I noticed the requirements.txt specifies `urllib3>=1.26.0,<2.0.0`

Is there any plan to support urllib3 v2?

**Comment by padamstx** [comment]
We do not yet have any plans to migrate to v2.

**Comment by padamstx** [comment]
We now have plans to migrate to v2 :)

**Comment by pyrooka** [comment]
Closing this issue as we already moved to v2 in [this commit](https://github.com/IBM/python-sdk-core/commit/d1ab40c941fb21be798461169a1937dbaf4de1de).
