### ISSUE TITLE
feat(auth): skip authentication

### ISSUE THREAD

**Issue by emlaver** [IBM/python-sdk-core#18]
Add a function like Java's `skipAuthentication` or Node's `options.use_unauthenticated` to [skip adding credentials to the `auth` parameter in `requests.request`](https://github.com/IBM/python-sdk-core/blob/master/ibm_cloud_sdk_core/base_service.py#L390-L394). 

This would allow for anonymous auth that, for example, can be used to connect to a CouchDB server with admin party mode enabled.

**Comment by ehdsouza** [comment]
NoAuthentication is supported in `v1.0.0`: https://github.com/IBM/python-sdk-core#no-authentication
