### ISSUE TITLE
Connecting to IBM Cloud through a proxy

### ISSUE THREAD

**Issue by itzzi** [IBM/python-sdk-core#31]
Hi! We are behind a proxy which needs authentication. We tried to pass the user, passw and proxies through the set_http_config() method:
```
http_config = {
   "proxies": {
         "http": "user:password@host:port"
     }
}
speech_to_text.set_http_config(http_config)
```
Still, we get a ‘407 proxy auth required’. We managed to send a request to IBM Cloud with `requests` library. However, when we try to replicate the behaviour with the sdk, we get the same error. It seems that when the token is requested in the IAM Token Manager (inside ibm_cloud_sdk_core), the proxies configuration is not included in the request… cause it fails connecting to iam.bluemix.net.

Thanks!

**Comment by germanattanasio** [comment]
HI @itzzi, thanks for reporting the issue. We are looking at it
