### ISSUE TITLE
service properties are removed from __read_from_vcap_services

### ISSUE THREAD

**Issue by ehdsouza** [IBM/python-sdk-core#54]
[commit](https://github.com/IBM/python-sdk-core/pull/41/files) updated the `__read_from_vcap_services` method where the keys like `url` and `disable_ssl` are ignored. 

When updating `vcap_service_credentials` with `new_vcap_creds`, the other keys are removed.

**Comment by padamstx** [comment]
Closing this one out, as the vcap stuff is essentially obsolete now.
