### ISSUE TITLE
Decoding access_token does not work with PyJWT v2.0.0

### ISSUE THREAD

**Issue by prince737** [IBM/python-sdk-core#88]
The requirement states `PyJWT >=1.7.1`, since PyJWT v2.0.0 was released, on a fresh install v2.0.0 is installed which throws the below error
![image](https://user-images.githubusercontent.com/31027320/103538282-f028f900-4ebb-11eb-9d6a-4963910c7ace.png)

**Comment by psschwei** [comment]
Looks like this the line causing the problem:
https://github.com/IBM/python-sdk-core/blob/master/ibm_cloud_sdk_core/jwt_token_manager.py#L71

For PyJMT v2.0+, the `verify` option was moved into the options dictionary, and so the updated code should be:

```python
decoded_response = jwt.decode(self.access_token, options={"verify_signature": False})
```

I'll open a PR for this shortly.

**Comment by padamstx** [comment]
This issue has been fixed in a recent version of the package.
