### ISSUE TITLE
requirements file issue with new core

### ISSUE THREAD

**Issue by mamoonraja** [IBM/python-sdk-core#95]
I tried switching from `3.3.4` to `3.3.5` and I am seeing the following error:

![image](https://user-images.githubusercontent.com/16810846/104056554-afccc200-51be-11eb-92b8-a918f814fd08.png)

**Comment by rmkeezer** [comment]
https://github.com/IBM/python-sdk-core/pull/94 solves this issue and has been included in 3.3.6. I needed to add a MANIFEST.in file to load the requirements.txt file in the setup.py requirements like in the sdk template.
